services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=phone_booking'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - '/var/lib/postgresql/data:/var/lib/postgresql/data'
