spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phone_booking
    username: myuser
    password: secret
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.type: trace
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}